name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console       
    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        files: /home/runner/work/EasyRulesDotNet/EasyRulesDotNet/EasyRulesDotNet.Tests/coverage.json
        fail_ci_if_error: true # optional (default = false)
        verbose: false # optional (default = false)
